### ISSUE TITLE
Is this in line with the PDFium licensing ?

### ISSUE THREAD

**Issue by erSitzt** [mlmdflr/win32-pdf-printer#1]
I found your library, but i'm curious if this is "free" to use..
At least you should add a disclaimer that this library is used

**Comment by mlmdflr** [comment]
Which part of the function do you use?

Only SumatraPDF related to print pdf api need to pay attention to his protocol.
He is using gpl3.0
can use print2 instead

**Comment by mlmdflr** [comment]
This part of the code will also be removed in the future

**Comment by erSitzt** [comment]
Thanks
